version: 2.1

jobs:
  dump-env:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Dump Environment Variables
          command: |
            env
            mkdir /tmp/artifacts
            printenv > /tmp/artifacts/env-vars.txt
      - store_artifacts:
          path: /tmp/artifacts
          destination: env-vars-artifacts

workflows:
  dump-env-workflow:
    jobs:
      - dump-env

