version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Create Artifact Files
          command: |
            mkdir /tmp/artifacts
            echo "This is a test artifact file." > /tmp/artifacts/artifact-1.txt
            echo "Another file here." > /tmp/artifacts/artifact-2.txt
      - store_artifacts:
          path: /tmp/artifacts
          destination: build-artifacts

workflows:
  create-artifact-workflow:
    jobs:
      - build
